### ISSUE TITLE
Gaussian Blur CreateInput bug

### ISSUE THREAD

**Issue by pufik1337** [HPCE/hpce-2017-cw5#10]
It looks like the CreateInput function of the Gaussian Blur puzzle only creates vectors where all values are 0. On line 162 of gaussian_blur.hpp:

`t=std::min(0.0f, std::max(1.0f, t));`

This can be fixed by swapping the min and max functions.

**Comment by m8pple** [comment]
Ah - that one I didn't notice because I use different code to generate the inputs
for that puzzle (as I was testing it on images and looking at the output - though
I didn't notice they were getting darker, which would have highlighted #6 ).

So fortunately not a breaking change, but thanks for spotting.

BTW, it's great the way you're digging deep in this way, particularly looking into
the actual values going past.
