### ISSUE TITLE
Gaussian Blur Constraints

### ISSUE THREAD

**Issue by TheoFranquet** [HPCE/hpce-2017-cw5#21]
Can I confirm with someone that there is an acceptable margin of error when validating the output of the blurring algorithm? 

This snippet is taken from the reference `gaussian_blur.hpp`:

![image](https://user-images.githubusercontent.com/22774033/32797295-3a0ec544-c969-11e7-93a0-a7d118e83426.png)

In other words, will the final grading for `gaussian_blur` be as tolerant as the comparison above?

**Comment by m8pple** [comment]
CompareOutput is part of the puzzle, so is intended to be _the_ definition of correctness ( any stupid bugs in my part not withstanding), So that tolerance should be considered to be part of the specification (in contrast, input creation is just an example, though it should be representative of typical inputs).
