### ISSUE TITLE
Call function from one class in another class 

### ISSUE THREAD

**Issue by natoucs** [HPCE/hpce-2017-cw5#33]
![screenshot from 2017-11-20 19-34-18](https://user-images.githubusercontent.com/12121636/33034971-d2ebd8f0-ce29-11e7-8518-a79c6e879ac9.png)

How can I call the `Execute` function in `heat_wolrd_v2.cpp`, from `heat_world.cpp` and in the same way that `ReferenceExecute` is being called ?

**Comment by guigzzz** [comment]
You can't. The only reason you can call ReferenceExecute from your puzzle solutions is that the puzzle solution classes inherit from the puzzle base class and hence have access to the functions present in the base class (including reference execute). You will need extra work to be able to do this as simply as execute and reference execute. What you can try doing is to put your other execute function in a header file and include that header file from the main puzzle solution header.

**Comment by m8pple** [comment]
As @guigzzz says, you can't because it is a member function. 

However, you _can_ create an instance of one of the classes then call the method.
For example, if you have another provider called `MiningProviderOther`, you could
do something like:
```
#include "mining_provider_other.hpp"

class MiningProvider
  : public puzzler::MiningPuzzle
{
public:
  MiningProvider()
  {}

	virtual void Execute(
			   puzzler::ILog *log,
			   const puzzler::MiningInput *input,
				puzzler::MiningOutput *output
			   ) const override
	{
                std::shared_ptr<puzzler::MiningPuzzle> pOther
                               =std::make_shared<MiningProviderOther>();

		pOther->Execute(log, input, output);
	}
};
```

You could also turn the member functions into straight functions, assuming they don't need
to make use of member variables.

**Comment by natoucs** [comment]
Thank you!
