### ISSUE TITLE
Caught exception : clEnqueueReadBuffer

### ISSUE THREAD

**Issue by kgiray** [HPCE/hpce-2017-cw5#36]
I am running the Gaussian Blur at GPU, 

Everything works fine until the read, here is my read command 

queue.enqueueReadBuffer(buffOutput, CL_TRUE, 0, cbBuffer, &outputPixels[0] );

and declaration of outputPixels is as follows 

std::vector<uint8_t> outputPixels(w*h, 0);

and cbBuffer is defined as 

size_t cbBuffer=w*h;

when queue.enqueueReadBuffer is executed it raises a exception : clEnqueueReadBuffer, do you have any idea why this might happen?

**Comment by m8pple** [comment]
I'm afraid without more information it is difficult to say, as there are many things that
could be going wrong. Bear in mind that it may not necessarily be the read that is
causing the problem - one of the earlier commands may have caused the problem,
but it appears at this point because you have indicated a synchronous read with the TRUE flag.

Common things which can cause it are:
- Host (CPU) buffers are not big enough for the transfer
- Target (GPU) buffers are not big enough for the transfer
- The kernels is reading or writing to invalid memory (i.e. outside a buffer)

You might try running it in a different provider (e.g. a software provider), and
see if it gives you more information when it crashes.

**Comment by kgiray** [comment]
Thanks @m8pple, I believe the issue was about using double precision numbers at GPU.
