### ISSUE TITLE
width and height for gaussian_blur

### ISSUE THREAD

**Issue by malharjajoo** [HPCE/hpce-2017-cw5#55]
Hi,

@m8pple  , Can we assume the width = height = scale **always** for gaussian_blur ?

From the CreateInput() in the reference file it seems to be the case, but would this be the same
during testing  ?

**Comment by m8pple** [comment]
I'm going to say no, simply because I can't remember what I chose for the final assessment.

The test input generation is always quantitatively/statistically similar to the examples though,
so the only change would be a small fuzzing amount (e.g. `width=height+(rand()%16)` or
similar). There wouldn't be anything where width=10 and height=10000000

**Comment by malharjajoo** [comment]
Ok, I asked this since if width = height, then the coefficient kernels would be completely identical.( which could save some time )
